services:
  - type: web
    name: guacamole
    env: docker
    plan: free
    image:
      url: guacamole/guacamole:latest
    envVars:
      - key: GUACAMOLE_AUTH_PROVIDER
        value: mysql
      - key: GUACAMOLE_HOME
        value: /home/guacamole
      - key: GUACD_HOSTNAME
        value: localhost
      - key: GUACD_PORT
        value: "4822"
      # Instead of fromSecret, pull from the group
      - fromGroup: guacamole-secrets # Use the name of your Environment Group here
    healthCheckPath: /guacamole
