services:
  - type: web
    name: guacamole
    env: docker
    plan: free
    image:
      url: guacamole/guacamole:latest
    envVars:
      - key: GUACAMOLE_AUTH_PROVIDER
        value: mysql
      - key: GUACAMOLE_HOME
        value: /home/guacamole
      - key: GUACD_HOSTNAME
        value: localhost
      - key: GUACD_PORT
        value: "4822"
      - key: GUACADMIN_PASSWORD
        value: Gu@va@1234# # FOR TESTING ONLY!
    healthCheckPath: /guacamole
