# render.yaml for Guacamole Web Service
# This configuration deploys the Guacamole web application and its guacd component.
# It assumes you have a separate database service (e.g., PostgreSQL or MySQL)
# and you will configure its connection details via environment variables.

services:
  - type: web
    name: guacamole-web
    env: docker
    # Use a stable Guacamole Docker image.
    # You can find official images on Docker Hub: https://hub.docker.com/r/guacamole/guacamole
    image: 
      url: guacamole/guacamole:1.5.3 # Consider using the latest stable version
    plan: free # Or 'standard' for more resources
    # Port 8080 is the default for Guacamole web application
    # Health check to ensure the service is running
    healthCheckPath: /guacamole/
  
